# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://ardux.io
title: ardux
email: "n/a"
description: "a one handed keyboard project"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: discord
    icon: discord
    url: https://discord.gg/fGUjnUuAVQ
  - title: github
    icon: github
    url: https://github.com/arduxio
